version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ricardo
      POSTGRES_USER: ricardo
      POSTGRES_DB: lens
    ports:
      - 5435:5432
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080